### ISSUE TITLE
View My Bookings

### ISSUE THREAD

**Issue by DragonizerX** [DragonizerX/CS3028-GroupAssignment-Kilo#21]
Able to view current bookings (possibly previous too).

**Comment by OliwierKam** [comment]
View README for bugs. Mostly complete however still need to implement the feature that bookings get done once calendar complete. DO NOT DELETE BOOKINGS. PLEASE. Delete function works however I need to create new bookings myself manually and it is a lot of effort.

SO PLEASE DONT DELETE BOOKINGS.

Feel free however to edit them as you please. Probably a lot of other things we can still add so let us know and we will look over it!
