### ISSUE TITLE
Reflects Equipment Database onto Calendar, option to add and delete equipment on Calendar Page.

### ISSUE THREAD

**Issue by Nat00n** [DragonizerX/CS3028-GroupAssignment-Kilo#31]
only admins

**Comment by DragonizerX** [comment]
Although that comment isn't wrong, the first part being "Reflects Equipment Database onto Calendar" must work for both User and Admin, assuming Nathan is working on this make sure its accurately reflected in the drop down rather than manual add in on the html.
