### ISSUE TITLE
Limit the maximum amount of bookings shown on a page.

### ISSUE THREAD

**Issue by DragonizerX** [DragonizerX/CS3028-GroupAssignment-Kilo#90]
As it says there has to be a limit to the amount of bookings we display on a singular page, find a good number and try to implement a page number system to display only a certain amount of them. This is required by most pages that could have an extensive list of bookings such as myBookings or Archive etc.

**Comment by OliwierKam** [comment]
Done for bookings, requests and archive. Once the css is cracked down for billings will also implement it there so lmk.
